"""Add status to Inquiry model

Revision ID: 3acab39d8cf1
Revises: 1eefeedc1cf2
Create Date: 2024-12-23 13:59:30.048391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acab39d8cf1'
down_revision = '1eefeedc1cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
