"""db reset

Revision ID: 2e809ff0d3b2
Revises: f04d22149bb6
Create Date: 2025-02-13 10:15:14.783914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e809ff0d3b2'
down_revision = 'f04d22149bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breaklog')
    # ### end Alembic commands ###
