"""delete dailycount's log_type

Revision ID: 55577e42193b
Revises: 2e809ff0d3b2
Create Date: 2025-02-13 10:40:13.871228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55577e42193b'
down_revision = '2e809ff0d3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dailycount', schema=None) as batch_op:
        batch_op.drop_column('log_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dailycount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_type', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
