"""Change user_id column to string

Revision ID: 7dd7f896bae7
Revises: 3acab39d8cf1
Create Date: 2024-12-23 14:28:29.691371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dd7f896bae7'
down_revision = '3acab39d8cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint('inquiry_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inquiry_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=80),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
