"""db reset

Revision ID: 85fa7470791d
Revises: 
Create Date: 2025-02-14 11:10:21.128554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fa7470791d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailycount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('final_standard_count', sa.Integer(), nullable=False),
    sa.Column('final_break_count', sa.Integer(), nullable=False),
    sa.Column('final_normal_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('normallog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('width_height', sa.String(length=10), nullable=False),
    sa.Column('tolerance_cm', sa.Integer(), nullable=False),
    sa.Column('standard_paper_size_cm', sa.Integer(), nullable=False),
    sa.Column('pixel_to_cm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standardlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standardlog')
    op.drop_table('paper_size')
    op.drop_table('normallog')
    op.drop_table('dailycount')
    op.drop_table('breaklog')
    # ### end Alembic commands ###
