"""empty message

Revision ID: 99403f6e65b1
Revises: 
Create Date: 2025-01-16 14:47:03.917188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99403f6e65b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cctv_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cctv_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_density', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('abnormal_behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('fall_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.cctv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.String(length=50), nullable=False),
    sa.Column('density_level', sa.String(length=50), nullable=False),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.cctv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_logs')
    op.drop_table('abnormal_behavior_logs')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('cctvs')
    # ### end Alembic commands ###
